name: id_disen
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.11.0=py37h06a4308_0
  - aiohttp=3.6.3=py37h7b6447c_0
  - astor=0.8.1=py37_0
  - async-timeout=3.0.1=py37_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py37_0
  - blosc=1.20.1=he1b5a44_0
  - brotli=1.0.9=he1b5a44_3
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2020.11.8=ha878542_0
  - cachetools=4.1.1=py_0
  - certifi=2020.11.8=py37h89c1867_0
  - cffi=1.14.3=py37h261ae71_2
  - chardet=3.0.4=py37h06a4308_1003
  - charls=2.1.0=he1b5a44_2
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=3.2.1=py37h3c74f83_1
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py37h8f50634_1
  - dask-core=2.30.0=py_0
  - decorator=4.4.2=py_0
  - freetype=2.10.4=h7ca028e_0
  - gast=0.2.2=py37_0
  - giflib=5.2.1=h36c2ea0_2
  - google-auth=1.23.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py37hf8bcb03_0
  - h5py=2.10.0=py37hd6299e0_1
  - hdf5=1.10.6=hb1b8bf9_0
  - idna=2.10=py_0
  - imagecodecs=2020.5.30=py37hda6ee5b_1
  - imageio=2.9.0=py_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - jpeg=9d=h36c2ea0_0
  - jxrlib=1.1=h516909a_2
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.3.1=py37hc928c03_0
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libaec=1.0.4=he1b5a44_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.13.0.1=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h4f3a223_6
  - libwebp-base=1.1.0=h36c2ea0_3
  - libzopfli=1.0.3=he1b5a44_0
  - lz4-c=1.9.2=he1b5a44_3
  - markdown=3.3.3=py37h06a4308_0
  - matplotlib-base=3.3.3=py37h4f6019d_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - multidict=4.7.6=py37h7b6447c_1
  - ncurses=6.2=he6710b0_1
  - networkx=2.5=py_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.3.1=h981e76c_3
  - openssl=1.1.1h=h516909a_0
  - opt_einsum=3.1.0=py_0
  - pillow=8.0.1=py37h63a5d19_0
  - pip=20.2.4=py37h06a4308_0
  - protobuf=3.13.0.1=py37he6710b0_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pyjwt=1.7.1=py37_0
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pywavelets=1.1.1=py37h161383b_3
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scikit-image=0.17.2=py37h10a2094_4
  - scipy=1.5.2=py37h0b6359f_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.15.0=py37h06a4308_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.33.0=h62c20be_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.0.0=gpu_py37h768510d_0
  - tensorflow-base=2.0.0=gpu_py37h0ec5d1f_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - tifffile=2020.11.18=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py37h4abf009_0
  - urllib3=1.25.11=py_0
  - werkzeug=0.16.1=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.2=py37h7b6447c_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - dlib==19.21.0
    - keras==2.3.1
    - mtcnn==0.1.0
    - opencv-python==4.4.0.46
    - pyyaml==5.3.1
    - tensorboard==2.0.2
    - tensorflow-addons==0.6.0
    - tensorflow-gpu==2.0.0
    - tqdm==4.53.0
